services:
  postgres:
    image: postgres:18.1
    container_name: expense_tracker_db
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin